name: Static analysis
on:
  pull_request:
  push:
    branches:
      - master
      - stable*
    paths:
      - 'lib/**'

permissions:
  contents: read

jobs:
  static-psalm-analysis:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ocp-version: [ 'v26.0.0', 'v27.0.0', 'dev-master']
        php-version: [ '8.2' ]

    name: Nextcloud ${{ matrix.ocp-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install dependencies
        run: composer require --dev nextcloud/ocp:${{ matrix.ocp-version }}

      - name: Install dependencies
        run: composer i

      - name: Run coding standards check
        run: composer run psalm
